export declare const poaTypes: readonly ["general", "limited", "durable", "medical", "vehicle", "tax", "springing", "other"];
export type PoaRequirementRecord = {
    id: string;
    jurisdiction: string;
    poa_type: string;
    ui_profile: string;
    notarization_rule: string;
    witness_rule: string;
    witness_count: number | null;
    durability_rule: string;
    statutory_form_rule: string;
    effective_date_rule: string;
    competency_rule: string;
    special_authority_rule: string;
    allows_agent_certification: boolean | null;
    requires_principal_signature: boolean | null;
    allows_proxy_signature: boolean | null;
    requires_acknowledgment_certificate: boolean | null;
    governing_law: string | null;
    execution_requirements_text: string | null;
    acknowledgment_witnessing_text: string | null;
    durability_text: string | null;
    special_authority_text: string | null;
    competency_text: string | null;
    statutory_form_text: string | null;
    effective_date_text: string | null;
    source_citation: string | null;
    source_url: string | null;
    review_status: string | null;
    reviewed_at: string | null;
    notes: string | null;
    created_at: string;
    updated_at: string;
};
export type PoaFormRuleRecord = {
    id: string;
    poa_requirement_id: string;
    statutory_form_exists: boolean;
    statutory_form_recommended: boolean;
    statutory_form_mandatory_for_product: boolean;
    must_track_statutory_ordering: boolean;
    must_track_statutory_headings: boolean;
    must_include_warning_to_principal: boolean;
    must_include_notice_to_agent: boolean;
    special_authorities_render_mode: "hidden" | "checklist" | "checklist_with_initials" | "checkboxes_from_statutory_form" | "freeform_text" | "hybrid" | "manual_review_only";
    freeform_special_authority_text_allowed: boolean;
    hybrid_rendering_allowed: boolean;
    attorney_customization_recommended: boolean;
    source_citation: string | null;
    source_url: string | null;
    legal_review_status: "pending" | "reviewed" | "needs_update" | "blocked";
    reviewed_at: string | null;
    reviewed_by: string | null;
    review_notes: string | null;
    created_at: string;
    updated_at: string;
};
export type PoaGlossaryTermRecord = {
    id: string;
    poa_requirement_id: string;
    glossary_key: string;
    generic_label: string;
    state_specific_label: string | null;
    product_description: string;
    why_user_needs_this: string | null;
    source_citation: string | null;
    source_url: string | null;
    is_materially_state_specific: boolean;
    legal_review_status: "pending" | "reviewed" | "needs_update" | "blocked";
    reviewed_at: string | null;
    reviewed_by: string | null;
    review_notes: string | null;
    sort_order: number;
    created_at: string;
    updated_at: string;
};
export type PoaSpecialAuthorityRuleRecord = {
    id: string;
    canonical_key: string;
    canonical_label: string;
    canonical_description: string;
    category: string | null;
    sort_order: number;
    is_core_national_key: boolean;
    explicitly_required: boolean;
    requirement_type: "express_grant" | "specific_language" | "separate_initials" | "statutory_form_checkbox" | "not_required" | "unclear";
    applies_to_general_financial_poa: boolean;
    statutory_form_only: boolean;
    custom_language_required: boolean;
    initials_required: boolean;
    checkbox_required: boolean;
    freeform_text_allowed: boolean;
    state_specific_label: string | null;
    statutory_text_excerpt: string | null;
    exact_statute_citation: string | null;
    source_url: string | null;
    plain_english_rule: string;
    confidence: "high" | "medium" | "low";
    legal_review_status: "pending" | "reviewed" | "needs_update" | "blocked";
    reviewed_at: string | null;
    reviewed_by: string | null;
    review_notes: string | null;
    effective_start_date: string | null;
    effective_end_date: string | null;
    renderer_metadata: Record<string, unknown>;
};
export type PoaRequirementDetails = {
    requirement: PoaRequirementRecord;
    formRules: PoaFormRuleRecord | null;
    glossary: PoaGlossaryTermRecord[];
    specialAuthorities: PoaSpecialAuthorityRuleRecord[];
};
export declare const getJurisdictionLabel: (jurisdiction: string) => string;
export declare const normalizeJurisdiction: (input: string) => string;
export declare const getPoaRequirement: (jurisdiction: string, poaType: (typeof poaTypes)[number]) => Promise<PoaRequirementRecord | null>;
export declare const getPoaRequirementDetails: (jurisdiction: string, poaType: (typeof poaTypes)[number]) => Promise<{
    requirement: PoaRequirementRecord;
    formRules: PoaFormRuleRecord | null;
    glossary: PoaGlossaryTermRecord[];
    specialAuthorities: PoaSpecialAuthorityRuleRecord[];
} | null>;
export declare const listPoaJurisdictions: (poaType: (typeof poaTypes)[number]) => Promise<{
    code: string;
    label: string;
}[]>;
//# sourceMappingURL=poaService.d.ts.map