insert into public.notification_templates (
  template_key,
  template_version,
  locale,
  channel,
  template_kind,
  audience_scope,
  trigger_event,
  invite_kind,
  subject_template,
  body_template,
  body_format,
  variables_schema,
  is_active,
  source_reference,
  metadata
)
values
  (
    'creator_remaining_signer_invites_sent_email',
    '2026.08.17.email.v1',
    'en-US',
    'email',
    'status_update',
    'registrant',
    'document.creator_remaining_signer_invites_sent',
    null,
    'Your signature is complete - invites sent',
    $$Hi {{firstName}},

Your signature is complete for {{documentName}} and DARCi sent the remaining signer invitations.

Open Documents to track the status:
{{documentsUrl}}

- Your DARCi Team$$,
    'markdown',
    '{"required":["firstName","documentName","documentsUrl"],"optional":["invitedSignerCount","invitedSignerNames"],"scope":[7]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#signing-invite-sent-status',
    '{"seed_source":"20260817_signing_in_app_notification_templates","route":"member_document"}'::jsonb
  ),
  (
    'creator_remaining_signer_invites_sent_email',
    '2026.08.17.in_app.v1',
    'en-US',
    'in_app',
    'status_update',
    'registrant',
    'document.creator_remaining_signer_invites_sent',
    null,
    'Invites sent',
    'Your signature is complete and the remaining signer invites were sent. Open Documents to track progress.',
    'text',
    '{"required":[],"optional":["documentId"],"scope":[7]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#signing-invite-sent-status',
    '{"seed_source":"20260817_signing_in_app_notification_templates","route":"member_document"}'::jsonb
  ),
  (
    'creator_remaining_signer_invites_sent_email',
    '2026.08.17.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'document.creator_remaining_signer_invites_sent',
    null,
    'Invites sent',
    'Your signature is complete and the remaining signer invites were sent.',
    'text',
    '{"required":[],"optional":["documentId"],"scope":[7]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#signing-invite-sent-status',
    '{"seed_source":"20260817_signing_in_app_notification_templates","route":"member_document"}'::jsonb
  ),
  (
    'signer_signed_update_email',
    '2026.08.17.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'invite.signer_completed',
    null,
    '{{signerName}} signed',
    '{{signerName}} completed their signature. Open Documents to review progress.',
    'text',
    '{"required":["signerName"],"optional":["documentId","remainingSignerCount"],"scope":[7]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#signing-status-in-app',
    '{"seed_source":"20260817_signing_in_app_notification_templates","route":"member_document"}'::jsonb
  ),
  (
    'signer_signed_update_email',
    '2026.08.17.in_app.v1',
    'en-US',
    'in_app',
    'status_update',
    'registrant',
    'invite.signer_completed',
    null,
    '{{signerName}} signed',
    '{{signerName}} completed their signature. Open Documents to review progress.',
    'text',
    '{"required":["signerName"],"optional":["documentId","remainingSignerCount"],"scope":[7]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#signing-status-in-app',
    '{"seed_source":"20260817_signing_in_app_notification_templates","route":"member_document"}'::jsonb
  ),
  (
    'all_signatures_complete_email',
    '2026.08.17.in_app.v1',
    'en-US',
    'in_app',
    'status_update',
    'registrant',
    'system.all_required_signatures_complete',
    null,
    'Signatures complete',
    'All required signatures are complete. Open Documents for the next step.',
    'text',
    '{"required":[],"optional":["documentId","requiresNotarization","nextDocumentStatus"],"scope":[7]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#signing-status-in-app',
    '{"seed_source":"20260817_signing_in_app_notification_templates","route":"member_document"}'::jsonb
  )
on conflict (template_key, template_version, locale, channel) do update
set template_kind = excluded.template_kind,
    audience_scope = excluded.audience_scope,
    trigger_event = excluded.trigger_event,
    invite_kind = excluded.invite_kind,
    subject_template = excluded.subject_template,
    body_template = excluded.body_template,
    body_format = excluded.body_format,
    variables_schema = excluded.variables_schema,
    is_active = excluded.is_active,
    source_reference = excluded.source_reference,
    metadata = public.notification_templates.metadata || excluded.metadata,
    updated_at = now();
