update public.notification_templates
set is_active = false,
    updated_at = now()
where locale = 'en-US'
  and channel = 'push'
  and is_active = true
  and template_key in (
    'member_signatures_recorded_email',
    'signer_invitation_email',
    'signer_reminder_email',
    'signer_completion_confirmation_email',
    'signer_signed_update_email',
    'notarization_submission_confirmation_email',
    'notary_request_claimed_email',
    'notary_application_approved_email',
    'notary_application_rejected_email'
  );

insert into public.notification_templates (
  template_key,
  template_version,
  locale,
  channel,
  template_kind,
  audience_scope,
  trigger_event,
  invite_kind,
  subject_template,
  body_template,
  body_format,
  variables_schema,
  is_active,
  source_reference,
  metadata
)
values
  (
    'member_signatures_recorded_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'member.document_signatures_confirmed',
    null,
    'Signature recorded',
    'Your signature was recorded. Open DARCi to review the current status.',
    'text',
    '{"required": [], "optional": ["documentId"], "scope": [3]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#wave-2',
    '{"seed_source":"20260810_wave2_push_templates","route":"document_signing"}'::jsonb
  ),
  (
    'signer_invitation_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'invite',
    'signer',
    'invite.document_signing_created',
    'document_signing',
    'Signature requested',
    'A document is ready for your review and signature in DARCi.',
    'text',
    '{"required": [], "optional": ["documentId"], "scope": [4]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#wave-2',
    '{"seed_source":"20260810_wave2_push_templates","route":"document_signing"}'::jsonb
  ),
  (
    'signer_reminder_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'reminder',
    'signer',
    'invite.document_signing_reminder',
    'document_signing',
    'Signature reminder',
    'Your signature is still needed. Open DARCi to continue.',
    'text',
    '{"required": [], "optional": ["documentId"], "scope": [6]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#wave-2',
    '{"seed_source":"20260810_wave2_push_templates","route":"document_signing"}'::jsonb
  ),
  (
    'signer_completion_confirmation_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'signer',
    'invite.document_signing_completed',
    null,
    'Signature received',
    'Your signature was received. Open DARCi to view the document status.',
    'text',
    '{"required": [], "optional": ["documentId"], "scope": [6]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#wave-2',
    '{"seed_source":"20260810_wave2_push_templates","route":"document_signing"}'::jsonb
  ),
  (
    'signer_signed_update_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'invite.signer_completed',
    null,
    'Signer completed',
    'A signer completed their step. Open DARCi to review progress.',
    'text',
    '{"required": [], "optional": ["documentId"], "scope": [7]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#wave-2',
    '{"seed_source":"20260810_wave2_push_templates","route":"document_signing"}'::jsonb
  ),
  (
    'notarization_submission_confirmation_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'member.notarization_submitted',
    null,
    'Submitted for illuminotarization',
    'Your document was submitted. Open DARCi to track progress.',
    'text',
    '{"required": [], "optional": ["requestId", "documentId"], "scope": [8]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#wave-2',
    '{"seed_source":"20260810_wave2_push_templates","route":"member_document"}'::jsonb
  ),
  (
    'notary_request_claimed_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'notary.code_resolved',
    null,
    'Illuminotary review started',
    'Your Illuminotary started reviewing the document. Open DARCi for status.',
    'text',
    '{"required": [], "optional": ["requestId", "documentId"], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#wave-2',
    '{"seed_source":"20260810_wave2_push_templates","route":"member_request"}'::jsonb
  ),
  (
    'notary_application_approved_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'client',
    'notary.application_approved',
    null,
    'Illuminotary profile approved',
    'Your Illuminotary profile was approved. Open DARCi to review settings.',
    'text',
    '{"required": [], "optional": [], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#wave-2',
    '{"seed_source":"20260810_wave2_push_templates","route":"user_settings"}'::jsonb
  ),
  (
    'notary_application_rejected_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'client',
    'notary.application_rejected',
    null,
    'Illuminotary profile update',
    'There is an update on your Illuminotary profile request. Open DARCi for details.',
    'text',
    '{"required": [], "optional": [], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#wave-2',
    '{"seed_source":"20260810_wave2_push_templates","route":"user_settings"}'::jsonb
  )
on conflict (template_key, template_version, locale, channel) do update
set template_kind = excluded.template_kind,
    audience_scope = excluded.audience_scope,
    trigger_event = excluded.trigger_event,
    invite_kind = excluded.invite_kind,
    subject_template = excluded.subject_template,
    body_template = excluded.body_template,
    body_format = excluded.body_format,
    variables_schema = excluded.variables_schema,
    is_active = excluded.is_active,
    source_reference = excluded.source_reference,
    metadata = public.notification_templates.metadata || excluded.metadata,
    updated_at = now();