insert into public.notification_templates (
  template_key,
  template_version,
  locale,
  channel,
  template_kind,
  audience_scope,
  trigger_event,
  invite_kind,
  subject_template,
  body_template,
  body_format,
  variables_schema,
  is_active,
  source_reference,
  metadata
)
values
  (
    'in_person_session_started_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'notary.meeting_started',
    null,
    'In-person session started',
    'Your Illuminotary is ready. Open DARCi to check in.',
    'text',
    '{"required": [], "optional": ["requestId", "documentId"], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#phase-5',
    '{"seed_source":"20260810_wave1_push_templates","route":"member_session"}'::jsonb
  ),
  (
    'notary_request_received_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'notary',
    'member.notary_selected',
    null,
    'New notarization request',
    'A new request is ready for review in DARCi.',
    'text',
    '{"required": [], "optional": ["requestId", "documentId"], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#phase-5',
    '{"seed_source":"20260810_wave1_push_templates","route":"notary_request_review"}'::jsonb
  ),
  (
    'notary_changes_requested_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'notary.changes_requested',
    null,
    'Changes requested',
    'Your Illuminotary needs an update before continuing.',
    'text',
    '{"required": [], "optional": ["requestId", "documentId"], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#phase-5',
    '{"seed_source":"20260810_wave1_push_templates","route":"member_document"}'::jsonb
  ),
  (
    'notary_request_rejected_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'notary.request_rejected',
    null,
    'Select another Illuminotary',
    'Your request needs a new Illuminotary in DARCi.',
    'text',
    '{"required": [], "optional": ["requestId", "documentId"], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#phase-5',
    '{"seed_source":"20260810_wave1_push_templates","route":"member_notary_selection"}'::jsonb
  ),
  (
    'notary_approval_received_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'notary.request_approved',
    null,
    'Request approved',
    'Your Illuminotary approved the request. Open DARCi for next steps.',
    'text',
    '{"required": [], "optional": ["requestId", "documentId"], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#phase-5',
    '{"seed_source":"20260810_wave1_push_templates","route":"member_request"}'::jsonb
  ),
  (
    'notary_member_contact_received_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'notary',
    'notary.request_approved',
    null,
    'Request approved',
    'Member coordination details are available in DARCi.',
    'text',
    '{"required": [], "optional": ["requestId", "documentId"], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#phase-5',
    '{"seed_source":"20260810_wave1_push_templates","route":"notary_request_review"}'::jsonb
  ),
  (
    'meeting_scheduled_confirmation_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'notary.meeting_scheduled',
    null,
    'Meeting scheduled',
    'Your in-person meeting schedule was updated in DARCi.',
    'text',
    '{"required": [], "optional": ["requestId", "documentId"], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#phase-5',
    '{"seed_source":"20260810_wave1_push_templates","route":"member_request"}'::jsonb
  ),
  (
    'document_ready_for_review_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'document.ready_for_review',
    null,
    'Documents ready',
    'Your documents are ready to review in DARCi.',
    'text',
    '{"required": [], "optional": ["documentId"], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#phase-5',
    '{"seed_source":"20260810_wave1_push_templates","route":"document_review"}'::jsonb
  ),
  (
    'member_signing_ready_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'document.signing_prepared',
    null,
    'Ready for signature',
    'Your documents are ready to sign in DARCi.',
    'text',
    '{"required": [], "optional": ["documentId"], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#phase-5',
    '{"seed_source":"20260810_wave1_push_templates","route":"document_signing"}'::jsonb
  ),
  (
    'all_signatures_complete_email',
    '2026.08.10.push.v1',
    'en-US',
    'push',
    'status_update',
    'registrant',
    'document.all_signatures_complete',
    null,
    'Signatures complete',
    'All required signatures are complete. Open DARCi for details.',
    'text',
    '{"required": [], "optional": ["documentId"], "scope": [11]}'::jsonb,
    true,
    'docs/push-notification-implementation-roadmap.md#phase-5',
    '{"seed_source":"20260810_wave1_push_templates","route":"member_document"}'::jsonb
  )
on conflict (template_key, template_version, locale, channel) do update
set template_kind = excluded.template_kind,
    audience_scope = excluded.audience_scope,
    trigger_event = excluded.trigger_event,
    invite_kind = excluded.invite_kind,
    subject_template = excluded.subject_template,
    body_template = excluded.body_template,
    body_format = excluded.body_format,
    variables_schema = excluded.variables_schema,
    is_active = excluded.is_active,
    source_reference = excluded.source_reference,
    metadata = public.notification_templates.metadata || excluded.metadata,
    updated_at = now();
