-- Seed trustee power options for all jurisdictions from docs/Trustee_powers.json.

with jurisdictions(jurisdiction) as (
  values
    ('US-CA'),
    ('US-OH'),
    ('US-AL'),
    ('US-AK'),
    ('US-AZ'),
    ('US-AR'),
    ('US-CO'),
    ('US-CT'),
    ('US-DE'),
    ('US-DC'),
    ('US-FL'),
    ('US-GA'),
    ('US-HI'),
    ('US-ID'),
    ('US-IL'),
    ('US-IN'),
    ('US-IA'),
    ('US-KS'),
    ('US-KY'),
    ('US-LA'),
    ('US-ME'),
    ('US-MD'),
    ('US-MA'),
    ('US-MI'),
    ('US-MN'),
    ('US-MS'),
    ('US-MO'),
    ('US-MT'),
    ('US-NE'),
    ('US-NV'),
    ('US-NH'),
    ('US-NJ'),
    ('US-NM'),
    ('US-NY'),
    ('US-NC'),
    ('US-ND'),
    ('US-OK'),
    ('US-OR'),
    ('US-PA'),
    ('US-RI'),
    ('US-SC'),
    ('US-SD'),
    ('US-TN'),
    ('US-TX'),
    ('US-UT'),
    ('US-VT'),
    ('US-VA'),
    ('US-WA'),
    ('US-WV'),
    ('US-WI'),
    ('US-WY')
),
powers(canonical_key, canonical_label, sort_order) as (
  values
    ('real_property', 'Real property', 10),
    ('personal_property', 'Personal property', 11),
    ('banking_and_financial', 'Banking and financial', 12),
    ('stocks_and_bonds', 'Stocks and bonds', 13),
    ('commodities_and_options', 'Commodities and options', 14),
    ('insurance_and_annuities', 'Insurance and annuities', 15),
    ('government_securities', 'Government securities', 16),
    ('margin_transactions', 'Margin transactions', 17),
    ('mutual_funds', 'Mutual funds', 18),
    ('claims_and_litigation', 'Claims and litigation', 19),
    ('business_operations', 'Business operations', 20),
    ('tax_matters', 'Tax matters', 21)
)
insert into public.trust_trustee_powers (
  jurisdiction,
  canonical_key,
  canonical_label,
  state_specific_label,
  sort_order,
  is_active,
  source_citation,
  source_url
)
select
  jurisdictions.jurisdiction,
  powers.canonical_key,
  powers.canonical_label,
  null,
  powers.sort_order,
  true,
  'docs/Trustee_powers.json',
  null
from jurisdictions
cross join powers
on conflict (jurisdiction, canonical_key) do update set
  canonical_label = excluded.canonical_label,
  state_specific_label = excluded.state_specific_label,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  source_citation = excluded.source_citation,
  source_url = excluded.source_url,
  updated_at = now();
